baseURL = "http://example.org/"
languageCode = "en-us"
title = "MiR Community Website"
theme = "basic"
relativeURLs = true

[params]
author = "Brian Hogan"
description = "My portfolio site"


[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"


[permalinks]
 webinars = "webinars/:year/:month/:slug"
 year = "/webinars/:slug/"
 month = "/webinars/:slug/"

[params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      email = "team@mircommunity.com"
   # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Team"
          url  = "team"
        [[params.footer.sitemap.link]]
          name = "Webinars"
          url  = "webinars"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/miR_community"
      # Footer Service
      [params.footer.service]
        title       =  "MiR Community"
        description = "MiR Community aims to support underrepresented R users around the world."